version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.0

jobs:
  test:
    docker:
      - image: cimg/node:lts-browsers  # Pre-installed with Chrome
    steps:
      - checkout
      - run:
          name: Verify Chrome
          command: |
            echo "Chrome path: $(which google-chrome)"
            google-chrome --version
            echo "ChromeDriver path: $(which chromedriver)"
            chromedriver --version
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run tests
          command: npm test
      - store_artifacts:
          path: tests_output
      - store_artifacts:
          path: screenshots

workflows:
  test-suite:
    jobs:
      - test