# .circleci/config.yml
version: 2.1

orbs:
  node: circleci/node@5.0.0 # Use the official Node.js orb

jobs:
  run-ui-tests:
    executor:
      name: node/default
      tag: '18.16.0' # Use a Node.js version compatible with your project

    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Chrome and ChromeDriver
          command: |
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
            # ChromeDriver is usually installed by `chromedriver` npm package,
            # but sometimes explicit installation of an apt package might be needed for system-wide access.
            # For this setup, we'll primarily rely on the npm package's installation,
            # but ensure Chrome is available.

      - run:
          name: Run Nightwatch UI Tests
          command: npm run test

workflows:
  version: 2
  build-and-test:
    jobs:
      - run-ui-tests