jobs:
  test:
    docker:
      - image: cimg/node:18.12-browsers
    working_directory: ~/project/ui-tests
    steps:
      - checkout:
          path: ~/project

      - run:
          name: Install latest Google Chrome
          command: |
            sudo apt-get update
            sudo apt-get install -y wget unzip gnupg
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt install ./google-chrome-stable_current_amd64.deb

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run Nightwatch UI tests (headless)
          command: npm test

      - store_artifacts:
          path: screenshots
          destination: screenshots

workflows:
  version: 2
  ui-tests:
    jobs:
      - test