version: 2.1

jobs:
  run-ui-tests:
    docker:
      - image: cimg/node:18.20.2-browsers
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            cd ui-tests
            npm install
            # Fix permissions for node_modules
            sudo chown -R circleci:circleci node_modules
            chmod -R 755 node_modules
            # Verify nightwatch executable
            ls -la node_modules/.bin/nightwatch
            chmod +x node_modules/.bin/nightwatch
      - run:
          name: Run UI Tests
          command: |
            cd ui-tests
            ./node_modules/.bin/nightwatch --env chrome_headless tests
      - store_artifacts:
          path: ui-tests/screenshots
          destination: screenshots

  run-api-tests:
    docker:
      - image: cimg/node:18.20.2
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install API Test Dependencies
          command: |
            cd api-tests
            npm install
      - run:
          name: Run API Tests
          command: |
            cd api-tests
            npm test

workflows:
  version: 2
  run-tests:
    jobs:
      - run-ui-tests
      - run-api-tests:
          requires:
            - run-ui-tests