version: 2.1

jobs:
  ui-test:
    docker:
      - image: cimg/node:18.12-browsers
    working_directory: ~/project/ui-tests
    steps:
      - checkout:
          path: ~/project

      - run:
          name: Install latest Google Chrome
          command: |
            sudo apt-get update
            sudo apt-get install -y wget unzip gnupg
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt install ./google-chrome-stable_current_amd64.deb

      - run:
          name: Install UI dependencies
          command: npm install

      - run:
          name: Run Nightwatch UI tests (headless)
          command: npm test

      - store_artifacts:
          path: screenshots
          destination: ui-test-screenshots

  api-test:
    docker:
      - image: cimg/node:18.12
    working_directory: ~/project/api-tests
    steps:
      - checkout:
          path: ~/project

      - run:
          name: Install API dependencies
          command: npm install

      - run:
          name: Fix Jest permission
          command: chmod +x ./node_modules/.bin/jest

      - run:
          name: Start API server in background
          command: |
            npm run dev &

      - run:
          name: Wait for API to be ready
          command: npx wait-on http://localhost:3000

      - run:
          name: Run API Tests
          command: npm test

      - store_artifacts:
          path: tests_output
          destination: api-test-results

workflows:
  version: 2
  test-all:
    jobs:
      - ui-test
      - api-test
