version: 2.1

jobs:
  test-api:
    docker:
      - image: cimg/node:18.20.2  # تأكدي من توافقه مع Node.js اللي بتستخدميه
    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: cd api-tests && npm install

      - run:
          name: Start server
          command: cd api-tests && nohup npm run dev > server.log 2>&1 &

      - run:
          name: Wait for server to be healthy
          command: npx wait-on http://localhost:3000/api/v1/healthcheck

      - run:
          name: Run API tests
          command: cd api-tests && npm test

workflows:
  version: 2
  test-all:
    jobs:
      - test-api
