version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.20.2-browsers  # ✅ Includes Chrome, Chromedriver, Node, NPM
    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            cd ui-tests
            npm install

      - run:
          name: Run Nightwatch tests (Chrome Headless)
          command: |
            cd ui-tests
            npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
