version: 2.1

executors:
  chrome-executor:
    docker:
      - image: cimg/node:18.20.2-browsers  # تحتوي على Chrome و ChromeDriver مدمجين
    working_directory: ~/project

jobs:
  run-ui-tests:
    executor: chrome-executor
    steps:
      - checkout
      - run:
          name: Install UI Test Dependencies
          command: |
            cd ui-tests
            npm install
      - run:
          name: Run Contact Test in Headless Mode
          command: |
            cd ui-tests
            npx nightwatch --env chrome_headless tests/contactTest.js
      - run:
          name: Run Home Test in Headless Mode
          command: |
            cd ui-tests
            npx nightwatch --env chrome_headless tests/homeTest.js

  run-api-tests:
    docker:
      - image: cimg/node:18.20.2
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install API Test Dependencies
          command: |
            cd api-tests
            npm install
      - run:
          name: Run API Tests
          command: |
            cd api-tests
            npm test

workflows:
  version: 2
  run-tests:
    jobs:
      - run-ui-tests
      - run-api-tests:
          requires:
            - run-ui-tests
