version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.20.2  # ✅ No need for preinstalled browsers
    working_directory: ~/project

    steps:
      - checkout

      - restore_cache:
          keys:
            - ui-tests-deps-{{ checksum "ui-tests/package-lock.json" }}
            - ui-tests-deps-

      - run:
          name: Install project dependencies
          command: |
            cd ui-tests
            npm install

      - save_cache:
          key: ui-tests-deps-{{ checksum "ui-tests/package-lock.json" }}
          paths:
            - ui-tests/node_modules

      - run:
          name: Run Nightwatch Tests
          command: |
            cd ui-tests
            npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
