version: 2.1

jobs:
  build:
    docker:
      - image: karthikiyengar/node-nightwatch:0.0.1  # Pre-installed Java, Selenium, Browsers, Drivers

    working_directory: ~/ui-tests

    steps:
      - checkout

      - run:
          name: Install Node.js dependencies
          command: npm install

      - run:
          name: Run Nightwatch Tests (Chrome)
          command: npm run test-chrome

workflows:
  version: 2
  build_and_test:
    jobs:
      - build