version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:18.20.2
    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Install dependencies
          working_directory: ~/project/api-tests
          command: npm install

      - run:
          name: Start mock-user-auth server
          working_directory: ~/project/api-tests
          command: |
            npm run dev &
            npx wait-on http://localhost:3000/api/v1/healthcheck

      - run:
          name: Run tests
          working_directory: ~/project/api-tests
          command: npm test

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
