version: 2.1

jobs:
  run-tests:
    docker:
      - image: cimg/node:18.19.0-browsers

    # This tells CircleCI to run commands inside the ui-tests folder
    working_directory: ~/project/ui-tests

    steps:
      # 1. Checks out the whole repository (Siemens-Task) to ~/project
      - checkout

      # From here on, all commands run inside ~/project/ui-tests

      # 2. Restore cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      # 3. Install dependencies (it will now find package.json)
      - run:
          name: Install Dependencies
          command: npm install

      # 4. Save cache
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      # 5. Run tests
      - run:
          name: Run Nightwatch Tests
          command: npm run test

      # 6. Store test results and artifacts
      - store_test_results:
          path: tests_output
      - store_artifacts:
          path: tests_output
      - store_artifacts:
          path: screenshots

workflows:
  version: 2
  build-and-test:
    jobs:
      - run-tests