version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.20-browsers  # ✅ يحتوي على Chrome و ChromeDriver جاهزين
    working_directory: ~/project/ui-tests

jobs:
  test:
    executor: node-executor
    steps:
      - checkout:
          path: ~/project

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Check system ChromeDriver version
          command: chromedriver --version

      - run:
          name: Run Nightwatch UI Tests in Headless Chrome
          command: npm test

      - store_artifacts:
          path: screenshots
          destination: screenshots

      - store_artifacts:
          path: tests_output
          destination: test_results

workflows:
  test-workflow:
    jobs:
      - test
