version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.20.2
    working_directory: ~/project/ui-tests  

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "ui-tests/package-lock.json" }}
            - dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "ui-tests/package-lock.json" }}

      - run:
          name: Run Nightwatch Tests
          command: npm test

workflows:
  version: 2
  test:
    jobs:
      - build
