version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.12.2-browsers  # Includes Node.js, Chrome, and Chromedriver

jobs:
  test-ui:
    executor: node-executor
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Run Nightwatch UI Tests (Headless Chrome)
          command: npm run test

      - store_artifacts:
          path: tests_output
          destination: test-reports

workflows:
  version: 2
  test-workflow:
    jobs:
      - test-ui
