version: 2.1

jobs:
  run-ui-tests:
    docker:
      - image: cimg/node:18.17.0-browsers
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            cd ui-tests
            npm install
      - run:
          name: Fix Nightwatch Permissions
          command: |
            cd ui-tests
            chmod +x ./node_modules/.bin/nightwatch
      - run:
          name: Run Contact Page Tests
          command: |
            cd ui-tests
            npx nightwatch --env default tests/contactTest.js
      - run:
          name: Run Home Page Tests
          command: |
            cd ui-tests
            npx nightwatch --env default tests/homeTest.js

workflows:
  version: 2
  run-tests:
    jobs:
      - run-ui-tests
