version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.12.2-browsers

jobs:
  test-ui:
    executor: node-executor
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Move into ui-tests folder
          command: cd ui-tests && npm install

      - run:
          name: Run Nightwatch UI Tests (Headless Chrome)
          command: cd ui-tests && npm run test

      - store_artifacts:
          path: ui-tests/tests_output
          destination: test-reports

workflows:
  version: 2
  test-workflow:
    jobs:
      - test-ui
