version: 2.1

jobs:
  test:
    docker:
      - image: cypress/browsers:node18.12.0-chrome107  # ✅ فيها Chrome و ChromeDriver
    working_directory: ~/project/ui-tests
    steps:
      - checkout:
          path: ~/project

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run Nightwatch UI tests (headless)
          command: npm test

      - store_artifacts:
          path: screenshots
          destination: screenshots

workflows:
  version: 2
  ui-tests:
    jobs:
      - test
