version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:11.15.0
    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            npm install

      - run:
          name: Start server in background
          command: |
            npm run dev &

      - run:
          name: Wait for healthcheck endpoint
          command: |
            npx wait-on http://localhost:3000/api/v1/healthcheck

      - run:
          name: Run tests
          command: |
            # هنا تحطي أمر تشغيل الاختبارات بتاعتك لو عندك

workflows:
  build_and_test:
    jobs:
      - build
