version: 2.1

jobs:
  ui-tests:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - run:
          name: Install UI dependencies
          working_directory: ui-tests
          command: npm install
      - run:
          name: Run UI tests
          working_directory: ui-tests
          command: npm test
      - store_artifacts:
          path: ui-tests/tests_output
      - store_artifacts:
          path: ui-tests/screenshots

  api-tests:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - run:
          name: Install API dependencies
          working_directory: api-tests
          command: npm install
      - run:
          name: Run API tests
          working_directory: api-tests
          command: npm test
      - store_artifacts:
          path: api-tests/test-results

workflows:
  version: 2
  test-all:
    jobs:
      - ui-tests
      - api-tests