version: 2.1

jobs:
  ui-test:
    docker:
      - image: cimg/node:18.12-browsers
    working_directory: ~/project/ui-tests
    steps:
      - checkout:
          path: ~/project

      - run:
          name: Install latest Google Chrome
          command: |
            sudo apt-get update
            sudo apt-get install -y wget unzip gnupg
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt install ./google-chrome-stable_current_amd64.deb

      - run:
          name: Install UI dependencies
          command: cd ui-tests && npm install

      - run:
          name: Run Nightwatch UI tests (headless)
          command: cd ui-tests && npm test

      - store_artifacts:
          path: ui-tests/screenshots
          destination: screenshots

  api-test:
    docker:
      - image: cimg/node:18.12
    working_directory: ~/project/api-tests
    steps:
      - checkout:
          path: ~/project

      - run:
          name: Install API dependencies
          command: cd api-tests && npm install

      - run:
          name: Ensure jest is executable
          command: chmod +x ./node_modules/.bin/jest

      - run:
          name: Run API tests
          command: cd api-tests && npm test

workflows:
  version: 2
  run-all-tests:
    jobs:
      - ui-test
      - api-test
