# .circleci/config.yml
version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  run-ui-tests:
    executor:
      name: node/default
      tag: '18.16.0' # Use a Node.js version compatible with your project

    steps:
      - checkout
      - run:
          name: Navigate to ui-tests directory
          command: cd ui-tests # Change directory before running npm commands
      - node/install-packages:
          pkg-manager: npm
          app-dir: ui-tests # Specify the directory where package.json is located relative to the project root

      - run:
          name: Install Chrome and ChromeDriver
          command: |
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
            # ChromeDriver is usually installed by `chromedriver` npm package.
            # We are ensuring Chrome is available.

      - run:
          name: Run Nightwatch UI Tests
          command: npm run test

      - store_artifacts:
          path: ui-tests/tests_output # Adjust path to be relative to the checkout directory
          destination: nightwatch-test-reports
      - store_artifacts:
          path: ui-tests/screenshots # Adjust path to be relative to the checkout directory
          destination: nightwatch-screenshots

workflows:
  version: 2
  build-and-test:
    jobs:
      - run-ui-tests