# .circleci/config.yml
version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  run-ui-tests:
    executor:
      name: node/default
      tag: '20.10.0' # <--- CHANGE THIS LINE to Node.js 20.x or higher

    steps:
      - checkout
      - run:
          name: Navigate to ui-tests directory
          command: cd ui-tests
      - node/install-packages:
          pkg-manager: npm
          app-dir: ui-tests

      - run:
          name: Install Chrome and ChromeDriver
          command: |
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable

      - run:
          name: Run Nightwatch UI Tests
          command: npm run test

      - store_artifacts:
          path: tests_output
          destination: nightwatch-test-reports
      - store_artifacts:
          path: screenshots
          destination: nightwatch-screenshots

workflows:
  version: 2
  build-and-test:
    jobs:
      - run-ui-tests