version: 2.1

jobs:
  run-tests:
    docker:
      - image: cimg/node:18.19.0-browsers

    # CHANGE THIS LINE:
    # Tell CircleCI to operate inside your project's subfolder.
    # Replace 'ui-tests' with the actual name of your folder.
    working_directory: ~/project/ui-tests

    steps:
      # 1. Get the code from your repository. This still checks out to ~/project.
      - checkout

      # The rest of the steps will now run inside ~/project/ui-tests,
      # where your package.json is located.

      # 2. Restore cached dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      # 3. Install all project dependencies (will now find package.json)
      - run:
          name: Install Dependencies
          command: npm install

      # 4. Save the dependency cache
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      # 5. Run your Nightwatch tests
      - run:
          name: Run Nightwatch Tests
          command: npm run test

      # 6. Store test results
      - store_test_results:
          path: tests_output

      # 7. Store artifacts
      - store_artifacts:
          path: tests_output
      - store_artifacts:
          path: screenshots

workflows:
  version: 2
  build-and-test:
    jobs:
      - run-tests