version: 2.1

jobs:
  run-ui-tests:
    docker:
      - image: cimg/node:18.20.2-browsers
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Google Chrome
          command: |
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
            echo "export CHROME_BIN=$(which google-chrome-stable)" >> $BASH_ENV
      - run:
          name: Install UI Test Dependencies
          command: |
            cd ui-tests
            npm install
            chmod +x node_modules/chromedriver/lib/chromedriver/chromedriver
      - run:
          name: Run UI Tests
          command: |
            cd ui-tests
            npm test
      - store_artifacts:
          path: ui-tests/screenshots
          destination: screenshots
      - store_artifacts:
          path: ui-tests/tests_output
          destination: test-reports

  run-api-tests:
    docker:
      - image: cimg/node:18.20.2
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install API Test Dependencies
          command: |
            cd api-tests
            npm install
      - run:
          name: Run API Tests
          command: |
            cd api-tests
            npm test

workflows:
  version: 2
  run-tests:
    jobs:
      - run-ui-tests
      - run-api-tests:
          requires:
            - run-ui-tests
