version: 2.1

executors:
  ui-executor:
    docker:
      - image: cimg/node:20.11.0-browsers
    working_directory: ~/project/ui-tests

  api-executor:
    docker:
      - image: cimg/node:20.11.0
    working_directory: ~/project/api-tests

jobs:
  ui-test:
    executor: ui-executor
    steps:
      - checkout:
          path: ~/project
          
      - run:
          name: Install latest Google Chrome
          command: |
            sudo apt-get update
            sudo apt-get install -y wget unzip gnupg
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - run:
          name: Install UI dependencies
          command: npm install

      - run:
          name: Run Nightwatch UI tests (headless)
          command: npm test

      - store_artifacts:
          path: screenshots
          destination: screenshots

  api-test:
    executor: api-executor
    steps:
      - checkout:
          path: ~/project

      - run:
          name: Install API dependencies
          command: npm install

      - run:
          name: Start Server & Run Tests
          command: |
            npm run dev &
            npm run wait
            npm test
            
      - store_artifacts:
          path: reports
          destination: reports

      - store_artifacts:
          path: coverage
          destination: coverage

workflows:
  test-all:
    jobs:
      - ui-test
      - api-test