version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.12.2-browsers

jobs:
  test-ui:
    executor: node-executor
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: cd ui-tests && npm install

      - run:
          name: Add node_modules/.bin to PATH
          command: echo 'export PATH=$PATH:./node_modules/.bin' >> $BASH_ENV

      - run:
          name: Make Nightwatch executable
          command: cd ui-tests && chmod +x ./node_modules/.bin/nightwatch

      - run:
          name: Run Nightwatch UI Tests (Chrome Headless)
          command: cd ui-tests && npm run test

      - store_artifacts:
          path: ui-tests/tests_output
          destination: test-reports

workflows:
  version: 2
  test-workflow:
    jobs:
      - test-ui
