version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.20.2  # Updated to use maintained CircleCI Node image
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
            - dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Run Nightwatch Tests (Headless Chrome)
          command: npm test

workflows:
  version: 2
  test:
    jobs:
      - build
