version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.20.2  # Lightweight Node image without browsers

    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Install Java Runtime (Required for Selenium)
          command: |
            sudo apt-get update
            sudo apt-get install -y default-jre

      - restore_cache:
          keys:
            - ui-tests-deps-{{ checksum "ui-tests/package-lock.json" }}
            - ui-tests-deps-

      - run:
          name: Install NPM Dependencies
          command: |
            cd ui-tests
            npm install

      - save_cache:
          key: ui-tests-deps-{{ checksum "ui-tests/package-lock.json" }}
          paths:
            - ui-tests/node_modules

      - run:
          name: Run Selenium & Nightwatch Tests
          command: |
            cd ui-tests
            npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
