version: 2.1

jobs:
  test-api:
    docker:
      - image: cimg/node:20.5.1

    working_directory: ~/project/api-tests

    steps:
      - checkout:
          path: ~/project

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Start server in background
          command: npm run dev &

      - run:
          name: Wait for server to be ready
          command: npx wait-on http://localhost:3000/api/v1/healthcheck

      - run:
          name: Run API Tests
          command: npm test

workflows:
  version: 2
  run-tests:
    jobs:
      - test-api
