version: 2.1

executors:
  chrome-node:
    docker:
      - image: cimg/node:20.6.1-browsers
    working_directory: ~/project/ui-tests  # نبدأ من داخل مجلد ui-tests مباشرة

jobs:
  test:
    executor: chrome-node
    steps:
      - checkout:
          path: ~/project  # 👈 نعمل checkout لجذر المشروع داخل مجلد project

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run Nightwatch UI tests (headless)
          command: npm test

      - store_artifacts:
          path: screenshots
          destination: screenshots

workflows:
  version: 2
  ui-tests:
    jobs:
      - test
