version: 2.1

executors:
  node-ui:
    docker:
      - image: cimg/node:18.12-browsers
    working_directory: ~/project/ui-tests

  node-api:
    docker:
      - image: cimg/node:18.12
    working_directory: ~/project/api-tests

jobs:
  ui-test:
    executor: node-ui
    steps:
      - checkout:
          path: ~/project

      - run:
          name: Install Google Chrome
          command: |
            sudo apt-get update
            sudo apt-get install -y wget unzip gnupg
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt install ./google-chrome-stable_current_amd64.deb

      - run:
          name: Install UI dependencies
          command: npm install

      - run:
          name: Run Nightwatch UI tests (headless)
          command: npm test

      - store_artifacts:
          path: screenshots
          destination: screenshots

  api-test:
    executor: node-api
    steps:
      - checkout:
          path: ~/project

      - run:
          name: Install API dependencies
          command: npm install

      - run:
          name: Start API server in background
          command: |
            nohup npx nodemon ./node_modules/mock-user-auth/bin/www.js > output.log 2>&1 &

      - run:
          name: Wait for server to be ready
          command: |
            npx wait-on http://localhost:3000

      - run:
          name: Run API tests
          command: npm test

      - store_artifacts:
          path: reports/test-report.html
          destination: api-test-report

      - store_artifacts:
          path: output.log
          destination: server-log

workflows:
  version: 2
  test-all:
    jobs:
      - api-test
      - ui-test
