version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:20.5.1

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Start mock server in background
          command: npm run dev &

      - run:
          name: Wait for server to be ready
          command: npx wait-on http://localhost:3000/api/v1/healthcheck

      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
