version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:18.16
    working_directory: ~/project/api-tests   # هنا نغير المسار لمجلد api-tests
    steps:
      - checkout
      
      - run:
          name: Install dependencies
          command: npm install
      
      - run:
          name: Start server
          command: npm run dev &
      
      - run:
          name: Wait for healthcheck endpoint
          command: npx wait-on http://localhost:3000/api/v1/healthcheck
      
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
