version: 2.1

executors:
  chrome-executor:
    docker:
      - image: cimg/node:18.20-browsers
    working_directory: ~/project/ui-tests

jobs:
  test:
    executor: chrome-executor
    steps:
      - checkout

      - run:
          name: Move to ui-tests folder
          command: cd ui-tests

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Run Nightwatch UI Tests in Headless Chrome
          command: npm test

      - store_artifacts:
          path: tests_output
          destination: test-results

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
