version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:18.20.2  # اختاري نسخة Node مناسبة لمشروعك
    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Change to api-tests directory
          command: cd api-tests && pwd

      - run:
          name: Install dependencies
          command: |
            cd api-tests
            npm install

      - run:
          name: Start server and wait for healthcheck
          command: |
            cd api-tests
            npm run dev &              # تشغيل السيرفر في الخلفية
            npx wait-on http://localhost:3000/api/v1/healthcheck

      - run:
          name: Run tests
          command: |
            cd api-tests
            npm test

workflows:
  version: 2
  run-tests:
    jobs:
      - test
