jobs:
  run-ui-tests:
    docker:
      - image: cimg/node:18.20.2
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install UI Test Dependencies
          command: |
            cd ui-tests
            npm install
      - run:
          name: Fix Nightwatch Permissions
          command: |
            cd ui-tests
            chmod +x ./node_modules/.bin/nightwatch  
      - run:
          name: Run UI Tests
          command: |
            cd ui-tests
            npx nightwatch tests/contactTest.js
            npx nightwatch tests/homeTest.js
