version: 2.1

jobs:
  api-test:
    docker:
      - image: cimg/node:18.12
    working_directory: ~/project/api-tests

    steps:
      - checkout:
          path: ~/project

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Start mock-user-auth server in background
          command: |
            nohup npx nodemon ./node_modules/mock-user-auth/bin/www.js > output.log 2>&1 &

      - run:
          name: Wait for server to be ready
          command: npx wait-on http://localhost:3000

      - run:
          name: Run API tests with Jest
          command: npm test

      - store_artifacts:
          path: output.log
          destination: server-log

      - store_artifacts:
          path: reports/test-report.html
          destination: api-test-report

workflows:
  version: 2
  test-workflow:
    jobs:
      - api-test
