version: 2.1

jobs:
  run-ui-tests:
    docker:
      - image: cimg/node:18.20.2-browsers
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Google Chrome
          command: |
            sudo apt-get update
            sudo apt-get install -y wget gnupg2
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google.gpg
            echo "deb [signed-by=/usr/share/keyrings/google.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
            google-chrome-stable --version
      - run:
          name: Install UI Test Dependencies
          command: |
            cd ui-tests
            npm install
            chmod +x ./node_modules/.bin/nightwatch
            chmod +x ./node_modules/chromedriver/lib/chromedriver/chromedriver
      - run:
          name: Run UI Tests
          command: |
            cd ui-tests
            export CHROME_BIN=$(which google-chrome-stable)
            npx nightwatch --env chrome_headless tests
      - store_artifacts:
          path: ui-tests/screenshots
          destination: screenshots
      - store_artifacts:
          path: ui-tests/tests_output
          destination: test-reports

  run-api-tests:
    docker:
      - image: cimg/node:18.20.2
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install API Test Dependencies
          command: |
            cd api-tests
            npm install
      - run:
          name: Run API Tests
          command: |
            cd api-tests
            npm test

workflows:
  version: 2
  run-tests:
    jobs:
      - run-ui-tests
      - run-api-tests:
          requires:
            - run-ui-tests
