version: 2.1

jobs:
  ui-test:
    docker:
      - image: cimg/node:18.12-browsers
    working_directory: ~/project/ui-tests
    steps:
      - checkout:
          path: ~/project

      - run:
          name: Install latest Google Chrome
          command: |
            sudo apt-get update
            sudo apt-get install -y wget unzip gnupg
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt install ./google-chrome-stable_current_amd64.deb

      - run:
          name: Install UI dependencies
          command: npm install

      - run:
          name: Run Nightwatch UI tests (headless)
          command: npm test

      - store_artifacts:
          path: screenshots
          destination: screenshots

  api-test:
    docker:
      - image: cimg/node:18.12
    working_directory: ~/project/api-tests
    steps:
      - checkout:
          path: ~/project

      - run:
          name: Install API dependencies
          command: npm install

      - run:
          name: Fix permissions for nodemon
          command: chmod +x ./node_modules/.bin/nodemon

      - run:
          name: Start API server in background
          command: |
            nohup npm run dev > output.log 2>&1 &
            sleep 5
            echo "Server started in background"

      - run:
          name: Wait for server to be ready
          command: |
            echo "Waiting for server on http://localhost:3000..."
            curl --retry 10 --retry-connrefused --retry-delay 2 http://localhost:3000 || (echo "Server did not respond" && cat output.log && exit 1)

      - run:
          name: Run API tests
          command: npm test

      - store_artifacts:
          path: output.log
          destination: server-log

workflows:
  version: 2
  test-all:
    jobs:
      - api-test
      - ui-test
