version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.20.2-browsers  # ✅ Pre-installed Chrome & ChromeDriver
    working_directory: ~/project

    steps:
      - checkout

      - restore_cache:
          keys:
            - ui-tests-deps-{{ checksum "ui-tests/package-lock.json" }}
            - ui-tests-deps-

      - run:
          name: Install dependencies for UI tests
          command: |
            cd ui-tests
            npm install

      - save_cache:
          paths:
            - ui-tests/node_modules
          key: ui-tests-deps-{{ checksum "ui-tests/package-lock.json" }}

      - run:
          name: Fix Nightwatch permissions
          command: |
            chmod +x ui-tests/node_modules/.bin/nightwatch

      - run:
          name: Run Nightwatch tests
          command: |
            cd ui-tests
            npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
