version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:18.20.2
    working_directory: ~/project  # 👈 غيرنا من api-tests إلى الجذر

    steps:
      - checkout

      - run:
          name: Move to api-tests directory
          command: cd api-tests

      - run:
          name: Install dependencies
          command: cd api-tests && npm install

      - run:
          name: Make binaries executable
          command: chmod +x ./api-tests/node_modules/.bin/*

      - run:
          name: Start server and wait for healthcheck
          command: |
            cd api-tests
            npm run dev &
            npx wait-on http://localhost:3000/api/v1/healthcheck

      - run:
          name: Run API Tests
          command: cd api-tests && npm test

workflows:
  version: 2
  run-tests:
    jobs:
      - test
