version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.20.2-browsers
    working_directory: ~/project  # Stay at root (not inside ui-tests)

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            cd ui-tests
            npm install

      - run:
          name: Run tests
          command: |
            cd ui-tests
            npm run test-chrome
