version: 2.1

jobs:
  ui-tests:
    docker:
      - image: cimg/node:lts-browsers  # Official CircleCI image with Chrome pre-installed
    steps:
      - checkout
      - run:
          name: Verify Chrome installation
          command: |
            google-chrome --version
            chromedriver --version
      - run:
          name: Install dependencies
          working_directory: ui-tests
          command: npm install
      - run:
          name: Run tests
          working_directory: ui-tests
          command: npm test
      - store_artifacts:
          path: ui-tests/tests_output
      - store_artifacts:
          path: ui-tests/screenshots

workflows:
  version: 2
  test-workflow:
    jobs:
      - ui-tests